name: paskar
description: کلاینت پیشرفته بازی‌های پاسور ایرانی
publish_to: "none"
version: 2.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  web_socket_channel:
  provider:
  shared_preferences:
  flutter_secure_storage:
  intl:
  url_launcher:
  share_plus:
  vibration:
  confetti:
  shimmer:
  flutter_spinkit:
  percent_indicator:
  flutter_animate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf