name: tgju_app
description: نبض بازار - شبکه اطلاع رسانی طلا، سکه، دلار و ارز
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  shared_preferences:
  http:
  fl_chart:
  shimmer:
  intl:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf