name: tgju_app
description: "نبض بازار - اپلیکیشن قیمت طلا، سکه، ارز و رمزارز"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  liquid_glass_widgets:
  http:
  html:
  provider:
  shared_preferences:
  path_provider:
  fl_chart:
  shimmer:
  url_launcher:
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf